/* SereniSuit - ECG beat-shape model (generated by ml/ecg_ptbdb_beats.py) */
#ifndef ECG_MODEL_H
#define ECG_MODEL_H
#ifdef __cplusplus
extern "C" {
#endif

#define ECG_BEAT_LEN   187      /* samples per beat, 125 Hz, 0..1, starts at the R-peak */
#define ECG_BEAT_FS    125
#define ECG_MODEL_PARAMS 28225

/* probability (0..1) that a beat's SHAPE looks like the dataset's "abnormal"
   class. Research signal only - not a diagnosis. */
float ecg_beat_abnormal_prob(const float *beat);

#ifdef __cplusplus
}
#endif
#endif
